import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Parallax Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

	    <Parallax pages={4}>

		    <ParallaxLayer
			    offset={0}
			    style={{
					backgroundColor: 'orange'
			    }}
		    >
			    <h1>Layer 1</h1>
		    </ParallaxLayer>
		    <ParallaxLayer
			    offset={1}
			    speed={0.5}
			    style={{
				    backgroundColor: 'yellow'
			    }}
		    >
			    <h1>Layer 2</h1>
		    </ParallaxLayer>

	    </Parallax>

	</div>
  )
}
